{{- if .Values.database.createSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "hive.secretName" . }}
  labels:
    {{- include "hive.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.database.passwordKey }}: {{ required "database.password is required when database.createSecret is true (use --set)" .Values.database.password | quote }}
{{- end }}
